### ISSUE TITLE
Why IronCheckedElementBehavior is not in PolymerElements/iron-behaviors?

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/iron-checked-element-behavior#10]

**Comment by notwaldorf** [comment]
Please see https://github.com/PolymerElements/iron-checked-element-behavior/issues/9#issuecomment-152457723. TL; DR: iron-behaviours was poorly named originally, and it's too late to do anything about that now.

**Comment by abdonrd** [comment]
Thanks @notwaldorf, your explanation makes perfect sense!

Maybe the best option is outsource the `IronButtonState` and the `IronControlState` in its own component? And add a deprecated warning in the `iron-behaviors` so we can remove the `iron-behaviors` in X time?
