### ISSUE TITLE
boolean factorization

### ISSUE THREAD

**Issue by Zecat** [PolymerElements/iron-checked-element-behavior#16]
``` js
return this.disabled || !this.required || (this.required && this.checked);
  is equivalent to
return this.disabled || !this.required || this.checked;
```

https://github.com/PolymerElements/iron-checked-element-behavior/blob/master/iron-checked-element-behavior.html#L81

**Comment by notwaldorf** [comment]
Yup, that makes sense! Would you mind sending a PR for that? :)
