### ISSUE TITLE
There is no documentation for Polymer.IronCheckedElementBehavior

### ISSUE THREAD

**Issue by CSEMike** [PolymerElements/iron-checked-element-behavior#4]
At least according to the popup when I try to click the documentation in paper-checkbox --
  https://elements.polymer-project.org/elements/paper-checkbox

**Comment by notwaldorf** [comment]
@frankiefu Do you know why the catalog is grumpy about this behaviour? I think I missed the how-to-get-behaviour-to-work-right-in-the-docs lesson maybe :(

**Comment by frankiefu** [comment]
I think couple things need to be fixed:
1) release a new version of `iron-elements` that contains the new `iron-checked-element-behavior`
2) in https://github.com/PolymerElements/paper-behaviors/blob/master/bower.json#L10, need to replace that with `paper-inky-focus-behavior.html`

That hopefully should do it.

**Comment by notwaldorf** [comment]
I did #1, going to crank out #2 real quick. Thanks!

**Comment by garlicnation** [comment]
Confirmed fixed locally and on https://elements.polymer-project.org/
