### ISSUE TITLE
iron-checked-element-behavior included in iron-elements

### ISSUE THREAD

**Issue by carolirod** [PolymerElements/iron-checked-element-behavior#5]
Just asking, iron-checked-element-behavior gonna be included either in the iron-elements package or in iron-behaviors right?
I saw it's been only one week since last update (as well as in the paper-toggle-button). So no hurry to include them but just to write down if I have to remove single dependancy afterwards or not, thanks!

**Comment by notwaldorf** [comment]
@carolirod Ah, sorry, I completely forgot to do that. On it! :)

**Comment by carolirod** [comment]
How quick response, thanks!
