### ISSUE TITLE
Merge into Polymer/iron-behaviors

### ISSUE THREAD

**Issue by teomaragakis** [PolymerElements/iron-checked-element-behavior#9]
Shouldn't this technically be a part of the iron-behaviors repository? It _is_ an iron behavior and many elements have to use both this and iron-behaviors. In my opinion it's more semantically correct to merge the two.

**Comment by notwaldorf** [comment]
It _is_ and iron-behavior, it's true, but as hindsight goes, we decided that putting _all_ the iron behaviours in the same repo doesn't make that much sense. Think of `iron-behaviors` as "the things you need to be able to interact with an element in the most basic way possible, and all other behaviors are bonuses.

In particular for this behaviour, more elements (like `paper-menu` or `paper-input`) would use `iron-behaviours`, but not `checked`, whereas only a couple of elements (checkboxes and radio buttons in particular) would use both. 

There are many other iron behaviours that have standalone repos: range, fit, overlay, menu, etc.

**Comment by teomaragakis** [comment]
Well, it doesn't make much sense to keep them as they are either. Iron-behaviors includes iron-button-state which combines very well with iron-checked-element-behavior. In fact, paper-checkbox uses both and it's logical to keep them together.

Nevertheless, I believe that the issue should stay open for a vote.
